#!/usr/bin/env bash
# Merge the Gruvbox theme in theme.conf into this machine's live limine.conf,
# and put the wallpaper where that theme points.
#
# Why merge instead of copy: Limine's boot entries here are generated by
# limine-entry-tool (from limine-mkinitcpio-hook) and by limine-snapper-sync.
# Overwriting limine.conf would delete every kernel entry and every Snapper
# snapshot entry. Those tools only ever rewrite entries, so the settings block
# at the top of the file is the part we own.
#
# Safe to re-run: the theme sits between markers and is replaced in place.
set -euo pipefail
src="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

BEGIN_MARK='### >>> gruvbox theme -- managed by dotfiles/config/.config/limine/install.sh'
END_MARK='### <<< gruvbox theme'

# Every setting the theme owns. Limine accepts both the British and American
# spellings of "colour", and the stock config ships the American ones commented
# out, so list both -- otherwise a re-run leaves two spellings of one setting.
KEYS='wallpaper|wallpaper_style|backdrop'
KEYS+='|interface_branding|interface_branding_colour|interface_branding_color'
KEYS+='|interface_help_colour|interface_help_color'
KEYS+='|interface_help_colour_bright|interface_help_color_bright'
KEYS+='|term_background|term_background_bright|term_foreground|term_foreground_bright'
KEYS+='|term_margin|term_margin_gradient|term_palette|term_palette_bright'

# --- find the live config -------------------------------------------------
# Same search order limine-entry-tool uses when ESP_PATH is unset.
esp=""
for d in /efi /boot /boot/efi /limine; do
  if sudo test -f "$d/limine.conf"; then esp="$d"; break; fi
done
[[ -n "$esp" ]] || {
  echo "!! No limine.conf found in /efi /boot /boot/efi /limine."
  echo "   Is limine installed and the ESP mounted?"
  exit 1
}
conf="$esp/limine.conf"

# Refuse to theme a config that has no entries: that would mean the real one
# lives somewhere else and we are about to decorate the wrong file.
entries=$(sudo grep -c '^/' "$conf" || true)
((entries > 0)) || {
  echo "!! $conf has no boot entries. Refusing to touch it."
  exit 1
}
echo ":: Live config: $conf ($entries OS entries -- these are not modified)"

# --- render the theme (before touching anything, so bad input fails early) --
[[ -r "$src/theme.conf" ]] || { echo "!! $src/theme.conf is missing."; exit 1; }
[[ -r "$src/sushi.jpg"  ]] || { echo "!! $src/sushi.jpg is missing."; exit 1; }

# Arch does not ship the `hostname` binary (it lives in inetutils, rarely
# installed), so read the name from systemd and fall back to the file.
host="$(hostnamectl --static 2>/dev/null || true)"
[[ -n "$host" ]] || host="$(cat /etc/hostname 2>/dev/null || true)"
[[ -n "$host" ]] || host="${HOSTNAME:-linux}"

tmpdir="$(mktemp -d)"
trap 'rm -rf "$tmpdir"' EXIT
sed "s/@HOSTNAME@/$host/g" "$src/theme.conf" > "$tmpdir/theme"
echo ":: Branding the menu as \"$host\""

# --- back up, outside the ESP so it does not eat boot-partition space ------
backup="$HOME/limine.conf-backup-$(date +%Y%m%d-%H%M%S)"
sudo cp "$conf" "$backup"
sudo chown "$USER" "$backup"
echo ":: Backed up to $backup"

# --- splice the theme into the settings block ------------------------------

# Everything before the first boot entry is the settings block. Strip any line
# that sets a key we own -- live or commented out, marked or hand-written --
# then append a fresh marked block. Entries are copied through untouched.
sudo cat "$conf" | awk \
  -v begin="$BEGIN_MARK" -v end="$END_MARK" \
  -v keys="$KEYS" -v themefile="$tmpdir/theme" '
  BEGIN { n = split(keys, k, "|"); for (i = 1; i <= n; i++) own[k[i]] = 1 }

  # From the first entry onward, copy verbatim.
  inentries || /^\// { inentries = 1; rest = rest $0 "\n"; next }

  $0 == begin { inblock = 1; next }
  $0 == end   { inblock = 0; next }
  inblock     { next }

  {
    bare = $0
    sub(/^[ \t]*#*[ \t]*/, "", bare)      # see through a commented-out setting
    split(bare, p, ":")
    if (p[1] in own) next
    if ($0 ~ /^### Theme/) next           # stock placeholder header

    # Deleting the old settings leaves their blank lines behind; collapse runs
    # of them so re-running does not slowly pad the top of the file.
    if ($0 ~ /^[ \t]*$/) { if (wasblank) next; wasblank = 1 } else wasblank = 0
    head = head $0 "\n"
  }

  END {
    printf "%s", head
    print begin
    while ((getline line < themefile) > 0) print line
    print end
    printf "%s", rest
  }
' > "$tmpdir/limine.conf"

# Sanity check before it goes anywhere near the boot partition.
new_entries=$(grep -c '^/' "$tmpdir/limine.conf")
((new_entries == entries)) || {
  echo "!! Entry count changed ($entries -> $new_entries). Aborting, nothing written."
  exit 1
}

sudo cp "$tmpdir/limine.conf" "$conf"
echo ":: Theme written ($new_entries OS entries intact)"

# --- wallpaper -------------------------------------------------------------
# theme.conf points at boot():/limine/sushi.jpg, which is this directory.
# Never put a file named limine.conf in here: Limine searches /limine/limine.conf
# before /limine.conf, so it would silently shadow the real config.
sudo install -Dm644 "$src/sushi.jpg" "$esp/limine/sushi.jpg"
echo ":: Wallpaper installed at $esp/limine/sushi.jpg"

# --- re-enroll, if this machine checksums its config -----------------------
# With enrollment on, an edited limine.conf will not boot until it is re-enrolled.
if sudo grep -rqs '^[[:space:]]*ENABLE_ENROLL_LIMINE_CONFIG=["'\'']\?yes' \
     /etc/default/limine /etc/limine-entry-tool.conf /etc/limine-entry-tool.d/; then
  echo ":: Config enrollment is on -- re-enrolling"
  sudo limine-enroll-config
fi

echo ":: Done. Reboot to see it. To undo: sudo cp $backup $conf"
