# ---- Limine theme: Gruvbox dark ----
timeout: 5
remember_last_entry: yes

wallpaper: boot():/limine/sushi.jpg
wallpaper_style: stretched

interface_branding: Arch Linux
interface_branding_colour: 8ec07c
interface_help_colour: 83a598

term_background: 90282828
term_foreground: ebdbb2
term_foreground_bright: fbf1c7
term_margin: 64
term_margin_gradient: 4
term_palette: 282828;cc241d;98971a;d79921;458588;b16286;689d6a;a89984
term_palette_bright: 928374;fb4934;b8bb26;fabd2f;83a598;d3869b;8ec07c;fbf1c7

# ---- entry below is unchanged ----

/Arch Linux (linux)
    protocol: efi
    path: boot():/EFI/Linux/arch-linux.efi
    cmdline: root=PARTUUID=075ecfe9-1fbe-42b9-b423-c16396259bc1 zswap.enabled=0 rw rootfstype=ext4
